export enum WorkType {
  DEVELOPMENT = 'DEVELOPMENT',
  TESTING = 'TESTING',
  REVIEW = 'REVIEW',
  PLANNING = 'PLANNING',
  MEETING = 'MEETING',
  DOCUMENTATION = 'DOCUMENTATION',
  SUPPORT = 'SUPPORT',
  OTHER = 'OTHER',
}
