export enum ProjectStatus {
  PLANNING    = 'PLANNING',
  IN_PROGRESS = 'IN_PROGRESS',
  ACTIVE      = 'ACTIVE',
  ON_HOLD     = 'ON_HOLD',
  TESTING     = 'TESTING',
  PRODUCTION  = 'PRODUCTION',
  BLOCKED     = 'BLOCKED',
  COMPLETED   = 'COMPLETED',
  CANCELLED   = 'CANCELLED',
}
